### PR TITLE
feat: add madfi-lens-followers-s01 group in playground

### PR DESCRIPTION
**Pull request by imthatcarlos**
## ClubSpace by Mad Finance ZK Badge
Mint this badge to show that you were an early supporter of Mad Finance, and get early access to ClubSpace - a live music NFT experience for web3 social.

https://twitter.com/madfiprotocol/status/1580690451597643776?s=20&t=EB16SorKmK_kqRAcLtpzZQ

Screen Shot 2022-10-21 at 12 25 55 PM

### CODE REVIEW

**Comment by leosayous21** [comment]
Hello @imthatcarlos, your ZK Badge looks really nice! 
It misses just the update of the `group-generators/generators/index.ts` file and I will be able to merge

**Comment by imthatcarlos** [comment]
Oops! Forgot that part - will take care in the next hour

**Comment by imthatcarlos** [comment]
hey @leosayous21 - all fixed!

**Review by leosayous21 — APPROVED** [review]

**Comment by leosayous21** [comment]
@imthatcarlos, it's merged, it will be available on https://playground.sismo.io/ in 5 minutes

**Pull request merged**
