### PR TITLE
Add eligible address

### PR DESCRIPTION
**Pull request by Thorchok**
Add one more eligible address: gosleep01.eth

### CODE REVIEW

**Comment by MartinGbz** [comment]
Hey @Thorchok it seems that @ RoRuneChad (on twitter) is the author of this group.
Do you have his authorization to modify it?

**Comment by Thorchok** [comment]
Hello!
I am RoRuneChad on Twitter 😅
I created that Christmas badge on Sismo but that day GitHub wasn't linked
to my account.
Thank you for fast response!

вт, 18 апр. 2023 г., 22:46 MartinGbz ***@***.***>:

**Comment by MartinGbz** [comment]
> Hello! I am RoRuneChad on Twitter 😅 I created that Christmas badge on Sismo but that day GitHub wasn't linked to my account. Thank you for fast response!

Oh okay ahah, perfect then!
I saw your message on twitter (it would have been better if you DMed me, but it's okay ahah)
I merge your PR 😊

**Comment by Thorchok** [comment]
I just wasn't sure if you read your DMs from strangers 😅
Thanks!
Have a good day.

вт, 18 апр. 2023 г., 23:56 MartinGbz ***@***.***>:

**Comment by MartinGbz** [comment]
Merged! Your group will be updated in ~30 minutes from now 😊

**Comment by Thorchok** [comment]
Awesome, thanks!

ср, 19 апр. 2023 г., 00:02 MartinGbz ***@***.***>:

**Pull request merged**
