### PR TITLE
feat: unstoppable domains group

### PR DESCRIPTION
**Pull request by sampolgar**
as per https://github.com/sismo-core/sismo-hub/issues/1449
I've added the 5 contract addresses for the `UNSRegistry` for both mainnet and polygon - I'm waiting for confirmation from unstoppable domains to see if  I should include more contracts

### CODE REVIEW

**Comment by MartinGbz** [comment]
Hey, all right! Let's wait their answer before merging it then :)

**Comment by sampolgar** [comment]
Yes, good to go

**Comment by MartinGbz** [comment]
Hey @sampolgar , they are some issues regarding the generation.
We have a rate limit because of the Promise.all(). Is it possible for you to make each call synchronously (and not asynchronously)?
Thanks! :)

**Comment by sampolgar** [comment]
Done! @MartinGbz

**Pull request merged**
