### PR TITLE
[factory]: Add new umanuma-lens-followers ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for umanuma-lens-followers group. 
 Generated from factory.sismo.io 
 Deposit transaction: https://etherscan.io/tx/0x3c0d5aecfcbd45f9cc8ee72f77d207f2409e7b73b5a5c6968c1b437d3b22b499

### CODE REVIEW

**Comment by yum0e** [comment]
Hey @miura415, can you provide a valid badge artwork please? You can see the guidelines here : https://www.notion.so/sismo/ZK-Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b

You can quickly create your badge artwork here: https://factory.sismo.io/svg-editor

If you want you can send me your image on my twitter here: [big_q__](https://twitter.com/big_q__)

**Comment by miura415** [comment]
> おい@miura415、有効なバッジのアートワークを提供していただけますか? ここでガイドラインを確認できます: https://www.notion.so/sismo/ZK-Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b
> 
> ここでバッジのアートワークをすばやく作成できます: https://factory.sismo.io/svg-editor
> 
> 必要に応じて、私の Twitter であなたの画像を送ってください: [big_q__](https://twitter.com/big_q__)

ok?
file:///Users/miura/Documents/%E6%9A%97%E5%8F%B7%E8%B3%87%E7%94%A3/NFT/zk_badge.svg

**Comment by miura415** [comment]
file:///Users/miura/Documents/%E6%9A%97%E5%8F%B7%E8%B3%87%E7%94%A3/NFT/zk_badge.svg

**Comment by miura415** [comment]
zk_badge

**Comment by miura415** [comment]
https://user-images.githubusercontent.com/60906090/212700398-bf8f1725-7a48-44d9-bf06-26b73a17cc55.svg

**Review by leosayous21 — APPROVED** [review]

**Pull request merged**
