### PR TITLE
[factory]: Add new friend-of-star ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for friend-of-star group. 
 Generated from factory.sismo.io 
 Deposit transaction: https://etherscan.io/tx/0x7b12275e08dc28f2e0fadbc398e92d64fac680f55e16db5ec890d06c7e76d87b

### CODE REVIEW

**Comment by yum0e** [comment]
Hey! You must provide an image inside a badge artwork to have your badge accepted. You can see the badge guidelines here: https://www.notion.so/sismo/ZK-Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b?pvs=4

**Comment by jemmyvv** [comment]
> Hey! You must provide an image inside a badge artwork to have your badge accepted. You can see the badge guidelines here: https://www.notion.so/sismo/ZK-Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b?pvs=4

Good morning sir. I have provided SVG file.

**Comment by yum0e** [comment]
Hey, you need to add your svg on top of the badge artwork, your svg is not currently following the guide style. Feel free to dm me the new badge artwork on Discord bigq#8629 or Twitter [big_q__](https://twitter.com/big_q__).

You can quickly do a new artwork on https://factory.sismo.io/svg-editor

**Comment by jemmyvv** [comment]
> 

OK,I sent a friend request to your discord.

**Review by yum0e — APPROVED** [review]

**Comment by yum0e** [comment]
Thanks for your contribution @jemmyvv! Your badge will be on https://app.sismo.io/friend-of-star in 15 minutes :)

**Pull request merged**
