### PR TITLE
group update 30.03.2023

### PR DESCRIPTION
**Pull request by aloeveruschka**
2 addresses added

### CODE REVIEW

**Review by johannafransn — APPROVED** [review]
Confirming that this add on with addresses is OK from my side (original group creator).

 @MartinGbz Will the added addresses now be part of the group automatically? On the sismo factory the badge connected to the group still says 8 eligable accounts, not sure if it just hasnt updated?

**Comment by aloeveruschka** [comment]
and another Q is it possible to correct the minting link please?

should be: 
https://app.sismo.io/?badge=liquality@ethdenver2023-hackathon

shows this:
image

**Comment by MartinGbz** [comment]
Hey @johannafransn @aloeveruschka you are right I need to compute the group again manually.
I'll merge the PR and compute the group just after.
I'll ping you once it's done :) Sorry for the oversight!

**Comment by MartinGbz** [comment]
@johannafransn @aloeveruschka your badge is now updated: https://app.sismo.io/?badge=liquality@ethdenver2023-hackathon :)

**Comment by aloeveruschka** [comment]
@MartinGbz thx a lot. I was able to mint with MM desktop (not on mobile), but the NFT won't show up in the MM mobile app... also no chance to import it. which wallets are working with it, and how?

Q  the badge detail page shows still a wrong count for eligible accounts and the referring PR. how will this update? will the mint link update?
image

**Pull request merged**
