### PR TITLE
[factory]: Add new cryptotelugu-x-debank ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for cryptotelugu-x-debank group. 
 Generated from factory.sismo.io

### CODE REVIEW

**Review by srom23 — APPROVED** [review]

**Review by srom23 — APPROVED** [review]
All good

**Comment by MartinGbz** [comment]
> All good

Hey thanks for your badge!
There is just an issue on the badge svg (image). Can you send me on Discord or Twitter which image did you want to use?
Only badges image using the factory will be accepted, it has to respect this style guide: https://www.notion.so/sismo/Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b

**Comment by harsharock** [comment]
> > All good
> 
> Hey thanks for your badge! There is just an issue on the badge svg (image). Can you send me on Discord or Twitter which image did you want to use? Only badges image using the factory will be accepted, it has to respect this style guide: https://www.notion.so/sismo/Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b

Kindly don't approve this. This is impersonator of official CryptoTelugu. This is not official owner of CryptoTelugu community.

**Comment by srom23** [comment]
> 

he is not but he just want to get the badage for his  community, as you can see creater twitter address .

**Comment by srom23** [comment]
> > All good
> 
> Hey thanks for your badge! There is just an issue on the badge svg (image). Can you send me on Discord or Twitter which image did you want to use? Only badges image using the factory will be accepted, it has to respect this style guide: https://www.notion.so/sismo/Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b

zk_badge

**Comment by harsharock** [comment]
> > 
> 
> he is not but he just want to get the badage for his community, as you can see creater twitter address .
> 
> so as i know its doesnt metter that only owner can post badage

Buddy, if it is for your community why are you using my logo and community name "CryptoTelugu" That is want called as impersonator . 

I would recommend to cancel this and create a new badge with your logos & name. Not the right way to get debank followers using my community name.


@MartinGbz MartinGbz Kindly reject this.

**Comment by harsharock** [comment]
> > > All good
> > 
> > 
> > Hey thanks for your badge! There is just an issue on the badge svg (image). Can you send me on Discord or Twitter which image did you want to use? Only badges image using the factory will be accepted, it has to respect this style guide: https://www.notion.so/sismo/Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b
> 
> Twitter https://twitter.com/CryptoTeluguO or just approve #874 . and close this, cryptotelugu-lens

why are you using my logo from #836 ?

 @MartinGbz kindly reject this he is trying to use my community name & logo.

**Comment by MartinGbz** [comment]
I close this PR, the new one is #874

**Pull request closed without merging**
