### PR TITLE
[factory]: Add new poolcleaner ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for poolcleaner group. 
 Generated from factory.sismo.io

### CODE REVIEW

**Comment by yum0e** [comment]
Hey @poolcleaner6, the group used and the description does not match for this badge. I understand that it was a test by reading the PR, I hope you liked your experience with the factory 😁
On another note, we are going to move badges created from the factory to Goerli and Mumbai testnets by default, you will also have the choice to issue your badge on the Gnosis chain. 
I am closing this PR but feel free to create another in the future!

**Comment by poolcleaner6** [comment]
Hey, can you tell me what was wrong?Photo or video?Or it’s other things?Sent using the mobile mail appOn 23.12.2022 at 09:42, bigq wrote:
                
            
            
                
                    From: "bigq" ***@***.***>Date: 23 December 2022To: "sismo-core/sismo-hub" ***@***.***>Cc: "Mention" ***@***.***>,"Stanislav Doroshenko" ***@***.***>Subject: Re: [sismo-core/sismo-hub] [factory]: Add new poolcleaner ZK Badge  (PR #460)
                
                

Hey @poolcleaner6, the group used and the description does not match for this badge. I understand that it was a test by reading the PR, I hope you liked your experience with the factory 😁

On another note, we are going to move badges created from the factory to Goerli and Mumbai testnets by default, you will also have the choice to issue your badge on the Gnosis chain.

I am closing this PR but feel free to create another in the future!

**Comment by yum0e** [comment]
Yeah sure, you are using the `sismo-early-users` group and explaining in your short description that you must be friend on twitter. The description does not fit with the group you created. Sismo early users are first users of Sismo, there is no link with Twitter accounts.

**Comment by poolcleaner6** [comment]
Can I create a new one, what will be okay with condition?Sent using the mobile mail appOn 23.12.2022 at 09:57, bigq wrote:
                
            
            
                
                    From: "bigq" ***@***.***>Date: 23 December 2022To: "sismo-core/sismo-hub" ***@***.***>Cc: "Mention" ***@***.***>,"Stanislav Doroshenko" ***@***.***>Subject: Re: [sismo-core/sismo-hub] [factory]: Add new poolcleaner ZK Badge  (PR #460)
                
                
Yeah sure, you are using the sismo-early-users group and explaining in your short description that you must be friend on twitter. The description does not fit with the group you created. Sismo early users are first users of Sismo, there is no link with Twitter accounts.

**Comment by yum0e** [comment]
I advise you to put a simple list of addresses instead of choosing a massive group like `ethereum-power-users`, it is not suiting well your description. I can't DM you on Twitter because you have closed your DMs but you can DM me if you want to talk about it in an easiest way. My twitter [@big_q__](https://twitter.com/big_q__)

**Pull request closed without merging**
