### PR TITLE
[factory]: Add new klmn ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for klmn group. 
 Generated from factory.sismo.io 
 Deposit transaction: https://goerli.etherscan.io/tx/0x36b07ad88914c6080dcf750e4a9d1ed214e4a3a3e0a49e69043e8659b599d140

### CODE REVIEW

**Review by ANTKLMN — APPROVED** [review]

**Review by ANTKLMN — APPROVED** [review]

**Review by ANTKLMN — APPROVED** [review]
Approve

**Review by ANTKLMN — APPROVED** [review]

**Comment by MartinGbz** [comment]
Hey @ANTKLMN, can you provide a valid badge artwork please?

You can see the style guide here : https://www.notion.so/sismo/ZK-Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b
And you can use the svg-editor tool on the factory to quickly have your badge visual: https://factory.sismo.io/svg-editor

Feel free to modify this pull request or send me the badge on twitter : [0xMartinGbz](https://twitter.com/0xMartinGbz) or discord.

Thanks!

**Comment by ANTKLMN** [comment]
KLMN1 (1)
@MartinGbz 👍

**Review by ANTKLMN — APPROVED** [review]

**Comment by MartinGbz** [comment]
Still does not respect badge guidelines sir...
Use this tool: https://factory.sismo.io/svg-editor

**Comment by ANTKLMN** [comment]
zk_badge (1)
Sorry

**Comment by MartinGbz** [comment]
Perfect thanks!

**Review by ANTKLMN — APPROVED** [review]

**Comment by MartinGbz** [comment]
You will see your badge in ~20 minutes at https://testnets.sismo.io/klmn :)

**Comment by ANTKLMN** [comment]
> You will see your badge in ~20 minutes at https://testnets.sismo.io/klmn :)

Thank you! ⭐

**Pull request merged**
