### PR TITLE
[factory]: Add new airdrop-alert-daily-followers-zk-badge ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for airdrop-alert-daily-followers-zk-badge group. 
 Generated from factory.sismo.io

### CODE REVIEW

**Comment by MartinGbz** [comment]
Hey, this seems to be a test.
Next week we are going to release a testnets where we will be able to send this type of ZK Badge.
I'm closing the PR, do not hesitate to create another one.

**Comment by nyssanida** [comment]
thanks

**Comment by nyssanida** [comment]
its on onling for Public? I want to share this badge to my Community

**Comment by MartinGbz** [comment]
> its on onling for Public? I want to share this badge to my Community

I closed the PR so it won't be published on sismo app.
The badge you created is only taking into account Sismo early users badge holders so that's why I though that was a test badge.
But you'll be free to create any badges after the release of the new app :)

**Pull request closed without merging**
