### PR TITLE
feat: add uniswap-contributors group on Goerli and Mumbai

### PR DESCRIPTION
**Pull request by ImmanuelXIV**
This is a PR following this tutorial: https://docs.sismo.io/sismo-docs/create-your-zk-badge/tutorial-for-developers.

### CODE REVIEW

**Comment by leosayous21** [comment]
Hey @ImmanuelXIV, this is a really nice group! 
The `uniswap_contributors.svg` is missing on the PR.
It should be added on the `static/badges/` folder
Thanks

**Comment by yum0e** [comment]
Thanks for your contribution @ImmanuelXIV! This badge looks very nice 😁 It will be on https://testnets.sismo.io in about 20 minutes

Do you have any feedback to give on the tutorial? We would be happy to know if you find some parts misleading or not too precise.

**Comment by ImmanuelXIV** [comment]
Thank you 😊.

Yes, I've got some suggestions to improve the tutorial. How do I best share
those with you? Can I create a PR for the tutorial?

**Comment by yum0e** [comment]
Hey, feel free to send me a friend request and a DM on Discord. It will be simpler to chat about your ideas 😁
Here is my discord bigq#8629

**Pull request merged**
