### PR TITLE
feat: add snapshot-gitcoindao-voters group in playground

### PR DESCRIPTION
**Pull request by andyswx**
This is a PR of the tutorial for making new sismo badges from https://docs.sismo.io/sismo-docs/devs-tutorials/create-your-zk-badge-in-15-minutes.

### CODE REVIEW

**Comment by leosayous21** [comment]
Hello @andyswx, well done for doing the tutorial! What do you want to do with this badge? The group seems to be the same as in the tutorial

**Comment by andyswx** [comment]
Hey @leosayous21 
I wanted to follow the end to end process for launching a badge on the playground before I launch our company's real badge. That way I'll learn the nuances behind creating a group and the badge.

**Comment by leosayous21** [comment]
Yes makes sense :-)

**Comment by leosayous21** [comment]
@andyswx Closing this PR, waiting for the new one :-) You can reach me on discord if needed

**Pull request closed without merging**
