### PR TITLE
[factory]: Add new milstan ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for milstan group. 
 Generated from factory.sismo.io 
 Deposit transaction: https://etherscan.io/tx/0xdc0a0875e3d6e3f1a42c3385db1fa9be4ee4bda92b9b4036d614acd2e1737fe3

### CODE REVIEW

**Comment by MartinGbz** [comment]
The tx you made is under 0.01 ETH (the Badge tokenId reservation fee), so we can't merge your badge.
You are free to create another one.

**Comment by milstan** [comment]
@MartinGbz however the status page still says "waiting for approval"
https://factory.sismo.io/explorer/24bd94d0-c767-45e2-be3d-278782dd5c9e

**Comment by MartinGbz** [comment]
> @MartinGbz however the status page still says "waiting for approval" https://factory.sismo.io/explorer/24bd94d0-c767-45e2-be3d-278782dd5c9e

Should be okay now :)

**Comment by milstan** [comment]
I still have the same message:

image

Tested on another browser too - not an issue of cache.

**Comment by MartinGbz** [comment]
Okay, it's because "guidelines not respected" label is not yet implemented in the factory. So the status will stay in "waiting for approval" for the moment. It will be available in the next factory update 👍

**Pull request closed without merging**
