### PR TITLE
Alchemy Provider 

### PR DESCRIPTION
**Pull request by pcardosolei**
- Adding Alchemy NFT API ( base case )

- Functions added getOwnersForCollection for a hackathon specific use case on the project supports multiple chains and erc. ( more info about the api https://docs.alchemy.com/reference/getownersforcollection)

- group generator created as an example.

### CODE REVIEW

**Comment by leosayous21** [comment]
Hey @pcardosolei, for the ALCHEMY_APP_TOKEN we need to add the env vars in the github action files. Can you follow the same pattern as the HIVE_API_KEY env vars to make all works?

**Comment by MartinGbz** [comment]
Hey @pcardosolei it seems not to work again because you use different names for the api key.
Can you just use `ALCHEMY_API_KEY` & `alchemy-api-key` everywhere? Thanks :)

**Comment by MartinGbz** [comment]
@pcardosolei so now the api key is well configured
But now the problem is that when generating the group, using the data provider, your axios request get an 404 error: https://github.com/sismo-core/sismo-hub/actions/runs/4452883452/jobs/7820969197?pr=1538#:~:text=%22AxiosError%3A%20Request%20failed,%7D

**Comment by pcardosolei** [comment]
> @pcardosolei so now the api key is well configured But now the problem is that when generating the group, using the data provider, your axios request get an 404 error: https://github.com/sismo-core/sismo-hub/actions/runs/4452883452/jobs/7820969197?pr=1538#:~:text=%22AxiosError%3A%20Request%20failed,%7D

it is quite strange. i'm running locally and it is generating.
Is there any variable from my side missing?

**Comment by MartinGbz** [comment]
I merged it on another branch in order for me to debug and test it :)

**Pull request merged**
