### PR TITLE
participant update 27/3/23

### PR DESCRIPTION
**Pull request by aloeveruschka**
added participants #27 to 32

### CODE REVIEW

**Comment by MartinGbz** [comment]
Hey @aloeveruschka, the group seems to be created by @/liquality_io (Twitter), so I need its authorization in order to merge your PR :/

**Review by johannafransn — APPROVED** [review]
Hi @aloeveruschka  & @MartinGbz , I created this group originally for Liquality, I approve Vera's request for extending the list further 👍

**Comment by aloeveruschka** [comment]
> Hey @aloeveruschka, the group seems to be created by @/liquality_io (Twitter), so I need its authorization in order to merge your PR :/

how does the 'authorization' work? can we add somewhere in the account github-handles?

**Comment by MartinGbz** [comment]
> > Hey @aloeveruschka, the group seems to be created by @/liquality_io (Twitter), so I need its authorization in order to merge your PR :/
> 
> how does the 'authorization' work? can we add somewhere in the account github-handles?

For now there is no really "authorization process", I just wanted to be sure that you weren't a random person that wanted to put his address in the group in order to mint the badge.
But now that I have the confirmation that is not the case, I'm gonna merge the PR 😊

**Pull request merged**
