### PR TITLE
[factory]: Add new b1y3-og-voters ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for b1y3-og-voters group. 
 Generated from factory.sismo.io

### CODE REVIEW

**Comment by yum0e** [comment]
Hey @8bit0x01, your PR looks nice but you didn't provide a badge. Feel free to open a new PR with a valid badge image or update this one with a valid image. Let us know what you will do 😁

**Comment by 8bit0x01** [comment]
> Эй @8bit0x01, Ваш пиар выглядит красиво, но вы не предоставили значок. Не стесняйтесь открывать новый PR с допустимым изображением значка или обновлять его с помощью действительного изображения. Дайте нам знать, что вы будете делать улыбка

For some reason I just can't insert an image into the poap))

**Comment by 8bit0x01** [comment]
> Hey @8bit0x01, your PR looks nice but you didn't provide a badge. Feel free to open a new PR with a valid badge image or update this one with a valid image. Let us know what you will do grin

For some reason I just can't insert an image into the poap))

**Comment by yum0e** [comment]
Can you try to make a badge with the factory svg editor please? Normally, it is straight forward
You can also try to do again a PR with a badge. 
https://factory.sismo.io/svg-editor

**Comment by 8bit0x01** [comment]
> Can you try to make a badge with the factory svg editor please? Normally, it is straight forward You can also try to do again a PR with an image on the badge. https://factory.sismo.io/svg-editor
See, I've inserted a picture, but it doesn't appear on the icon. I'll try it on PC soon

Thank you!)
Screenshot_20230110-173232
Screenshot_20230110-173240

**Comment by yum0e** [comment]
I think it is an issue on our side, the factory is not meant to be accessible on mobile. Thanks for pointing this error! Can I ask which phone do you have please? I think that you will have a better time on PC 😁

**Comment by 8bit0x01** [comment]
> 



> I think it is an issue on our side, the factory is not meant to be accessible on mobile. Thanks for pointing this error! Can I ask which phone do you have please? I think that you will have a better time on PC 😁

Oh yes, of course you can!)

Google Pixel 3a + Brave browser - a killer bunch of newbie-cryptan😁

If you’re not pleas, I have a question for you ... is it possible to write the description and the title text in Russian or Ukrainian, for example?) And I also want to know if it’s possible to add a link to my telegram channel ?

As soon as everything works out, I will definitely leave you a review. Thanks for the help!)

**Comment by yum0e** [comment]
Thank you very much! 

You can find all the information about badge curation here https://www.notion.so/sismo/ZK-Badge-Curation-Guidelines-a62b5d7205734b44b41c603bf1516f4c
The playground is being deprecated starting today, but you can just acknowledge that in order to have a curated badge one day you need to follow these rules. The link to a telegram channel is totally okay but will you have to stick to English language in order to be understood by everyone if it is okay for you 😁

**Comment by 8bit0x01** [comment]
I just tried it through a PC, but now on this page https://factory.sismo.io/, even when accessing from a computer, it still writes a message stating that it is impossible to create on mobile.

Sorry, but I have never dealt with the code manually, so I need this simple way😁

**Comment by yum0e** [comment]
You are seeing an error message on your computer? Seems weird, what is the computer? 

You can create a whole new PR on https://factory.sismo.io/ don't worry

**Comment by 8bit0x01** [comment]
I started to get acquainted with gnosisSafe) As it turned out, in terms of security, I have superficial knowledge, but at the level of a beginner. Is that why you laugh all the time?

Sorry for the hype on Discord 👽

**Comment by 8bit0x01** [comment]
> You are seeing an error message on your computer? Seems weird, what is the computer?
> 
> You can create a whole new PR on https://factory.sismo.io/ don't worry

Yes, yesterday I tried it from a friend's computer through TeamViewer. Continued to write that I was coming from the phone. It seems to be yes, but the session was started from the PC))

**Comment by yum0e** [comment]
I would definitely advice you to test it on a PC without TeamViewer or anything. It can lead to edge cases if not done this way. 

You are pushing our tech too far I think 😇

**Comment by 8bit0x01** [comment]
My friend, the whole problem is that I don't have it, and for a very long time. Therefore, like this.

**Comment by yum0e** [comment]
Here is my twitter, you can send me your image if you want. 

https://twitter.com/big_q__

**Comment by 8bit0x01** [comment]
@yum0e 
Sorry, but I've been sitting brainstorming all day🤣 I think I'm starting to understand...

Tux, I see you have added a badge to the Mumbai network, but GnosisSafe does not have this network.

I hope my thinking is correct

**Comment by 8bit0x01** [comment]
Screenshot_20230112-162308

**Comment by 8bit0x01** [comment]
@yum0e I saw that I need to somehow verify the api. I'll figure it out now 😁

**Comment by 8bit0x01** [comment]
Also, in the addresses suitable for minting, I entered my public address on which there is an ens domain, is this not a mistake or a problem?) If so, is it possible to do something so that you add another address from which I could mint

**Pull request merged**
