### PR TITLE
[factory]: Add new jiraya-og-nft ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for jiraya-og-nft group. 
 Generated from factory.sismo.io

### CODE REVIEW

**Comment by sjdjz** [comment]
# using ssh
git clone git@github.com:sismo-core/sismo-hub.git
cd sismo-hub

**Comment by sjdjz** [comment]
yarn

**Comment by sjdjz** [comment]
docker compose up

**Comment by leosayous21** [comment]
Invalid Badge SVG.
Talk with JiRaYa_OG on tweet, he is going to re-create the PR with a valid badge

**Pull request closed without merging**
