### PR TITLE
[factory]: Add new orange-dao-contributors ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for orange-dao-contributors group. 
 Generated from factory.sismo.io 
 Deposit transaction: https://etherscan.io/tx/0xe3a89e2d2c16fb3128e620e2f2799c089683ab3260fdbb934e09a5f291cde111

### CODE REVIEW

**Comment by yum0e** [comment]
Hey! You will need to embed your svg on a badge visual to have your PR accepted.

You can quickly create the badge on https://factory.sismo.io/svg-editor. Here is the style guide https://www.notion.so/sismo/ZK-Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b

You can update this PR with the new badge SVG or send me the svg directly on twitter [big_q__](https://twitter.com/big_q__)

**Comment by hsuperman** [comment]
orange_zk_badge
thank you - let me know if this works! @yum0e

**Comment by yum0e** [comment]
Hey @hsuperman, thanks for your badge artwork! As you can see your group is not generated with success though. 

It comes from your API endpoint that only has one address in this format:
```bash
0x10B8C5Fc95b261F03834fF11311d975D353AedE9
```

If you could please change to this format on your API endpoint, it can resolve your issue 😁
```json
{ "0x10B8C5Fc95b261F03834fF11311d975D353AedE9": 1}
```

Let us know when it is done, so that we can run again the check and accept your badge. Thanks!

**Comment by hsuperman** [comment]
thank you @yum0e ! i've updated it
i added a second address as well, to confirm how to add more in the future. is the format correct for two?
thank you!

**Review by yum0e — APPROVED** [review]

**Comment by yum0e** [comment]
Thanks a lot for @hsuperman! You will see your badge on https://app.sismo.io/orange-dao-contributors in about 30 minutes 😁 

If you have any feedbacks on the factory, don't hesitate to add me on Discord to discuss about it bigq#8629

**Pull request merged**
