### PR TITLE
[factory]: Add new cryptotelugu-x-debank ZK Badge

### PR DESCRIPTION
**Pull request by srom23**
This PR adds a new ZK Badge for cryptotelugu-x-debank group.
Generated from factory.sismo.io
And Edited By me as per "https://github.com/sismo-core/sismo-hub/pull/859#issuecomment-1374460476"

### CODE REVIEW

**Comment by harsharock** [comment]
Kindly don't approve this. This is impersonator of official CryptoTelugu. This is not official owner of CryptoTelugu community.

**Comment by MartinGbz** [comment]
Hey, thank you for your PR!
Next week we will push an update, and will be able to send this type of ZK Badge on testnets and other chains.
So that's why we will wait until next week before merging it.
Thank you for your understanding :)

**Comment by srom23** [comment]
> Kindly don't approve this. This is impersonator of official CryptoTelugu. This is not official owner of CryptoTelugu community.


i dont know you are real harsha last time, bro i am helping you and your community to have zk playground Badge, they asked for creater twitter so puted mine in this pr but below i also added your twitter.

your lens badage is for only lens holder so i throught why not make one for all debank follow back form user.

i am not imposter i just willing that your community should have one badge .

if i impost i will make new twiiter similler to your name and content.

please understand what i want to say.

**Comment by harsharock** [comment]
> > Kindly don't approve this. This is impersonator of official CryptoTelugu. This is not official owner of CryptoTelugu community.
> 
> i dont know you are real harsha last time, bro i am helping you and your community to have zk playground Badge, they asked for creater twitter so puted mine in this pr but below i also added your twitter.
> 
> your lens badage is for only lens holder so i throught why not make one for all debank follow back form user.
> 
> i am not imposter i just willing that your community should have one badge .
> 
> if i impost i will make new twiiter similler to your name and content.
> 
> please understand what i want to say.

I understand your concern buddy. But as far as i know there is no option to find our debank followers and give badge minting option & I don't know which debank link you shared. if those details are wrong it may be misleading. That's why I don't want anyone else to use my logos & community name.

**Comment by MartinGbz** [comment]
Okay so regarding @harsharock messages I'm closing this PR

**Comment by srom23** [comment]
> 

no bro let it closed but i used your follow back spreadseed [this link](https://docs.google.com/spreadsheets/d/1ERGuyJerhvrHC97A-qjGBJPTdpyQHFXKt9foHjbA9TQ/edit?usp=sharing)

### _And there is  option to find our debank followers_ 
just send Get Requset
https://api.debank.com/user/followers?id=0xc5c408ec4c61a905ce45d41162b83ef2e06fcca0&start=0&limit=3000


thank you for your time to talk .

**Comment by harsharock** [comment]
> > 
> 
> no bro let it closed but i used your follow back spreadseed [this link](https://docs.google.com/spreadsheets/d/1ERGuyJerhvrHC97A-qjGBJPTdpyQHFXKt9foHjbA9TQ/edit?usp=sharing)
> 
> ### _And there is option to find our debank followers_
> just send Get Requset https://api.debank.com/user/followers?id=0xc5c408ec4c61a905ce45d41162b83ef2e06fcca0&start=0&limit=3000
> 
> thank you for your time to talk .

I am really sorry buddy, I misunderstood you.
I was not aware that u used my Debank wallet followers.

Because there are many impersonators out there on many platforms. I was just worried that's all.

Thanks for sharing this information bro.

Kindly text me on my telegram @harsharock45

**Comment by MartinGbz** [comment]
Don't hesitate to create a new PR after the release of the new app frens 🤗

**Pull request closed without merging**
