### PR TITLE
[factory]: Add new isaac-essuman ZK Badge 

### PR DESCRIPTION
**Pull request by sismobot**
This PR adds a new ZK Badge for isaac-essuman group. 
 Generated from factory.sismo.io 
 Deposit transaction: https://goerli.etherscan.io/tx/0x0331ab2e56ab4869ca5e9c407ee0c2218f03387e9bb7527e1e8de66dbd476856

### CODE REVIEW

**Comment by MartinGbz** [comment]
Hey your badge does not respect the badge svg guideline (https://www.notion.so/sismo/Badge-Artwork-Style-Guide-921d853497fb45efb17459c1ed30c24b), can you provide me a new image for your badge? On twitter [0xMartinGbz](https://twitter.com/0xMartinGbz) or Discord martingbz.eth#3809
Thanks!

**Comment by isaacessuman** [comment]
> martingbz.eth#3809

Hello Martin, I have sent you the badge via your Twitter dm

**Comment by MartinGbz** [comment]
Thanks! You will see your badge in ~20 minutes at https://testnets.sismo.io/isaac-essuman

**Comment by isaacessuman** [comment]
Gracias Mucho comrade

**Pull request merged**
